main:
    steps:
    - parallelTasks:
        parallel:
            branches:
                - opaPropertiesPipeline:
                    steps:
                    - extractPropertyData:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_opa_properties'
                            auth:
                                type: OIDC
                    - preparePropertyData:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/prepare_opa_properties'
                            auth:
                                type: OIDC
                    - loadPropertyData:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/load_opa_properties'
                            auth:
                                type: OIDC

                - opaAssessmentsPipeline:
                    steps:
                    - extractAssessments:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_opa_assessments'
                            auth:
                                type: OIDC
                    - prepareAssessments:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/prepare_opa_assessments'
                            auth:
                                type: OIDC
                    - loadAssessments:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/load_opa_assessments'
                            auth:
                                type: OIDC
                
                - pwdParcelsPipeline:
                    steps:
                    - extractPWDParcels:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_pwd_parcels'
                            auth:
                                type: OIDC
                    - preparePWDParcels:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/prepare_pwd_parcels'
                            auth:
                                type: OIDC
                    - loadPWDParcels:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/load_pwd_parcels'
                            auth:
                                type: OIDC
                
                - neighborhoodsPipeline:
                    steps:
                    - extractNeighborhoods:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_neighborhoods'
                            auth:
                                type: OIDC
                    - prepareNeighborhoods:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/prepare_neighborhoods'
                            auth:
                                type: OIDC
                    - loadNeighborhoods:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/load_neighborhoods'
                            auth:
                                type: OIDC

                - landmarksPipeline:
                    steps:
                    - extractLandmarks:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_landmarks'
                            auth:
                                type: OIDC
                
                - marketsPipeline:
                    steps:
                    - extractMarkets:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_markets'
                            auth:
                                type: OIDC

                - crimesPipeline:
                    steps:
                    - extractCrimes:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_crimes'
                            auth:
                                type: OIDC
                
                - request311Pipeline:
                    steps:
                    - extract311:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_311'
                            auth:
                                type: OIDC    
    - model:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/model'
          auth:
            type: OIDC
    
    - modelToTable:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/model_to_table'
          auth:
            type: OIDC
    
    - createTableForJson:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/create_table_for_json'
          auth:
            type: OIDC
    
    - parallelTasks2:
        parallel:
            branches:
                - jsonForCharts:
                    steps:
                    - phillyChart:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/generate_philadelphia_assessment_chart_configs'
                            auth:
                                type: OIDC
                    - neighborhoodChart:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/generate_neighborhood_assessment_chart_configs'
                            auth:
                                type: OIDC
                - tilesForMaps:
                    steps:
                    - propertyInfo:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/property_tiles_info'
                            auth:
                                type: OIDC
                    - runCloudRunJob:
                        call: http.post
                        args:
                            url: 'https://us-east1-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/musa5090s25-team5/jobs/generate-property-map-tiles:run'
                            auth:
                                type: OAuth2
                            headers:
                                Content-Type: application/json
                            body: {}
    