main:
    steps:
    - parallelTasks:
        parallel:
            branches:
                - opaPropertiesPipeline:
                    steps:
                    - extractPropertyData:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_opa_properties'
                            auth:
                                type: OIDC
                    - preparePropertyData:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/prepare_opa_properties'
                            auth:
                                type: OIDC
                    - loadPropertyData:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/load_opa_properties'
                            auth:
                                type: OIDC

                - opaAssessmentsPipeline:
                    steps:
                    - extractAssessments:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_opa_assessments'
                            auth:
                                type: OIDC
                    - prepareAssessments:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/prepare_opa_assessments'
                            auth:
                                type: OIDC
                    - loadAssessments:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/load_opa_assessments'
                            auth:
                                type: OIDC
                
                - pwdParcelsPipeline:
                    steps:
                    - extractPWDParcels:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/extract_pwd_parcels'
                            auth:
                                type: OIDC
                    - preparePWDParcels:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/prepare_pwd_parcels'
                            auth:
                                type: OIDC
                    - loadPWDParcels:
                        call: http.post
                        args:
                            url: 'https://us-east4-musa5090s25-team5.cloudfunctions.net/load_pwd_parcels'
                            auth:
                                type: OIDC
